import type { Metadata } from "next";
import "./globals.css";
import "./buttons.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const env = process.env.NEXT_PUBLIC_ENVIRONMENT;
  return (
    <html lang="en">
      <body className="bg-darkBackground p-6 text-lightGrayText">
        {env === "demo" && (
          <div className="text-xl text-center absolute z-10 bg-white rounded-md text-darkBackground px-2 py-1">
            This is a demo
          </div>
        )}
        {children}
      </body>
    </html>
  );
}
