import "../globals.css";
import "../buttons.css";
import ClientInitializer from "@/utils/ClientIntializer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-darkBackground text-lightGrayText">
        <ClientInitializer>{children}</ClientInitializer>
      </body>
    </html>
  );
}
