import "../globals.css";
import "../buttons.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-darkBackground p-6 text-lightGrayText">
        {children}
      </body>
    </html>
  );
}
